### ISSUE TITLE
Remove tailwindcss import in `ng-milkdown` componet

### ISSUE THREAD

**Issue by biquanneng** [ousc/ng-milkdown#1]

**Comment by biquanneng** [comment]
Thanks for your work.

In `ng-milkdown` component

```
  template: `
      <div #editorRef [hidden]="loading" class="milkdown-editor" [class]="classList"></div>
      @if (loading) {
          <ng-container *stringTemplateOutlet="spinner">loading...</ng-container>
      }
  `,
  styles: [
    `
      @import "tailwindcss/base";
      @import "tailwindcss/components";
      @import "tailwindcss/utilities";

      :host {
        display: contents;
      }
    `
  ]
```

![image](https://github.com/ousc/ng-milkdown/assets/25541695/64168515-8d6d-40a2-aa62-e4a7cbdcf097)

We should import `tainlwindcss` in app if needed, rather than import in base component, and it can occur 404 error for loading css.

Thanks again for your contribution!

**Comment by ousc** [comment]
> Thanks for your work.
> 
> In `ng-milkdown` component
> 
> ```
>   template: `
>       <div #editorRef [hidden]="loading" class="milkdown-editor" [class]="classList"></div>
>       @if (loading) {
>           <ng-container *stringTemplateOutlet="spinner">loading...</ng-container>
>       }
>   `,
>   styles: [
>     `
>       @import "tailwindcss/base";
>       @import "tailwindcss/components";
>       @import "tailwindcss/utilities";
> 
>       :host {
>         display: contents;
>       }
>     `
>   ]
> ```
> 
> ![image](https://github.com/ousc/ng-milkdown/assets/25541695/64168515-8d6d-40a2-aa62-e4a7cbdcf097)
> 
> We should import `tainlwindcss` in app if needed, rather than import in base component, and it can occur 404 error for loading css.
> 
> Thanks again for your contribution!
> 
> 
> 
> 
> 
> 


You are right, and I will create a PR  to fix it ASAP.
